- src/app/app.module.ts
- src/app/header/header.component.html
- src/app/header/header.component.ts
- src/app/shared/material/material.module.ts
- src/app/shared/modals/registration/registration.component.html
- src/app/shared/modals/registration/registration.component.scss
- src/app/shared/modals/registration/registration.component.spec.ts
- src/app/shared/modals/registration/registration.component.ts
Added registration modal window.
> Added registration modal window. #24

- src/app/app.component.html
- src/app/app.module.ts
- src/app/footer/footer.component.html
- src/app/footer/footer.component.spec.ts
- src/app/footer/footer.component.ts
- src/app/shared/directives/digit-only.directive.spec.ts
> Us#23 footer

- src/app/shell/main/filters-list/age-filter/age-filter.component.ts
> add close modal by clicking outside

- .github/workflows/tests.yml
- package.json
- yarn.lock
> upgrade GitHub actions

- src/app/shared/models/activity.model.ts
- src/app/shared/models/child-activities.model.ts
- src/app/shared/services/children-activities-list/children-activities-list.service.spec.ts
- src/app/shared/services/children-activities-list/children-activities-list.service.ts
- src/app/shared/store/user.actions.ts
- src/app/shared/store/user.state.ts
- src/app/shell/geolocation.service.ts
- src/app/shell/parent/parent-activities/child-activities/child-activities.component.html
- src/app/shell/parent/parent-activities/child-activities/child-activities.component.scss
- src/app/shell/parent/parent-activities/child-activities/child-activities.component.spec.ts
- src/app/shell/parent/parent-activities/child-activities/child-activities.component.ts
- src/app/shell/parent/parent-activities/parent-activities.component.html
- src/app/shell/parent/parent-activities/parent-activities.component.scss
- src/app/shell/parent/parent-activities/parent-activities.component.ts
- src/app/shell/parent/parent.module.ts
- src/assets/mock-children-activities-list.json
> create parent activity page

- src/app/shared/components/filters-list/city-filter/city-filter.component.ts
- src/app/shared/store/user-registration.state.ts
- src/app/shell/shell.module.ts
1. User-reg state was fixed
2. missed imports were added to modules 
3. Paths to components and guards are fixed
> user reg state fixing+ modules

- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/shell/provider/provider.module.ts
1. To the provider module HttpClientModule was added to imports
2. The link to get back to the main page was added to the "Позішкілля", text-decoration and color-changing was taken away
> fixing+ link to get back to the main page

- src/app/app.module.ts
- src/app/shared/store/parent.actions.ts
- src/app/shared/store/parent.state.ts
- src/app/shared/store/provider.actions.ts
- src/app/shared/store/provider.state.ts
- src/app/shell/parent/parent-activities/parent-activities.component.ts
- src/app/shell/parent/parent-config/parent-config.component.ts
- src/app/shell/parent/parent.module.ts
- src/app/shell/provider/provider-activities/provider-activities.component.ts
- src/app/shell/provider/provider.module.ts
1. Two additional states were created (provider, parent)
2. Use of services were moved to the corresponding states
3. States were added to the corresponding child modules.
> #116 state refactoring

- src/app/shared/modals/registration/registration.module.ts
- src/app/shared/services/local-session-manager/local-session-manager.service.spec.ts
- src/app/shared/services/local-session-manager/local-session-manager.service.ts
- src/app/shared/store/registration.state.ts
ISSUE: Needs to click login button after refreshing to get session again
Added local-session-manager service that saves the user session
> LocalSessionManagerService

- src/app/shared/components/create-teacher/teacher-form/teacher-form.component.html
- src/app/shared/models/child.model.ts
- src/app/shell/personal-cabinet/parent/parent-config/parent-config.component.html
- src/app/shell/personal-cabinet/parent/parent-create-child/child-form/child-form.component.html
- src/app/shell/personal-cabinet/parent/parent-create-child/parent-create-child.component.html
- src/app/shell/personal-cabinet/parent/parent-info/parent-info.component.html
- src/app/shell/personal-cabinet/parent/parent-routing.module.ts
- src/app/shell/shell-routing.module.ts
1. Option to delete teacher and child appears only if there more than 1 child/teacher
2. fix for  broken child form (it was duplicated)
3. fix of create-child routing
> fix fo create chidl and create teahcer

- src/app/shared/mocks/mock-services.ts
- src/app/shared/models/workshop.model.ts
- src/app/shared/store/meta-data.actions.ts
- src/app/shared/store/meta-data.state.ts
- src/app/shared/store/user.state.ts
- src/app/shell/personal-cabinet/parent/create-child/create-child.component.spec.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.spec.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.ts
1. Added functionality for the checkbox (if checked to use provider information for form fields)
2. Fixed the workshop model (there were new required fields on the back-end) and added new formControls for them
3. Added new action that can clear the state from categories. Otherwise, when we create our second workshop - we still have the same categories displayed for the user.
> #230 checkbox for create workshop

- src/app/shared/components/workshop-card/workshop-card.component.html
- src/app/shared/enum/provider.ts
- src/app/shared/store/app.actions.ts
- src/app/shared/store/user.state.ts
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.html
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.scss
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.spec.ts
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
- src/app/shell/personal-cabinet/personal-cabinet.component.html
- src/app/shell/personal-cabinet/personal-cabinet.component.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.ts
- src/app/shell/personal-cabinet/provider/provider-org-info/provider-org-info.component.html
- src/app/shell/personal-cabinet/provider/provider-org-info/provider-org-info.component.ts
- src/app/shell/personal-cabinet/workshops/workshops.component.ts
- src/app/shell/shell-routing.module.ts
- src/app/shell/workshop-details/side-menu/actions/actions.component.html
- src/app/shell/workshop-details/workshop-details.component.ts
1. Added workshop to the create application, so now the application is linked to the appropriate workshop
2. Fixed linked from the result component to the workshop details
**NEEDS STYLING!:)**
> linked workshop  card to the application

- src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.html
- src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.spec.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.ts
@myroslav-melnychenko everything works fine! Next time be more attentive:)
Grab next task!!!
> #230 checkbox for same address

- src/app/shell/personal-cabinet/provider/create-workshop/create-teacher/teacher-form/teacher-form.component.html
Fix for a max length of teacher description textarea
> Teacher max length fix

- src/app/shared/models/user.model.ts
- src/app/shared/store/user.state.ts
- src/app/shell/personal-cabinet/user-config/user-config-edit/user-config-edit.component.html
- src/app/shell/personal-cabinet/user-config/user-config-edit/user-config-edit.component.spec.ts
- src/app/shell/personal-cabinet/user-config/user-config-edit/user-config-edit.component.ts
- src/app/shell/personal-cabinet/user-config/user-config.component.ts
> fix edit user mode

- src/app/header/header.component.html
- src/app/header/header.component.ts
Replaced subscription on MainPageView with new functionality of page tracking
> final header fix

- src/app/shared/services/workshops/user-workshop/user-workshop.service.ts
- src/app/shared/store/user.actions.ts
- src/app/shared/store/user.state.ts
- src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-workshop.component.ts
- src/app/shell/personal-cabinet/user-config/user-config-edit/user-config-edit.component.spec.ts
- src/app/shell/personal-cabinet/user-config/user-config-edit/user-config-edit.component.ts
- src/app/shell/personal-cabinet/workshops/workshops.component.html
- src/app/shell/personal-cabinet/workshops/workshops.component.ts
- src/app/shell/workshop-details/workshop-details.component.ts
Provider can get its workshops by provider Id in its personal cabinet
Parent still have all workshops
> Provider can get its workshops by Provider Id

- src/app/shared/store/registration.state.ts
- src/app/shared/store/user.actions.ts
- src/app/shared/store/user.state.ts
Create Parent flow is removed because it is handled on the back-end
> removed create parent flow

- src/app/shared/registration/registration.module.ts
> Authorization

- src/app/shared/enum/applications.ts
- src/app/shared/models/application.model.ts
- src/app/shared/services/applications/application.service.ts
- src/app/shared/store/user.actions.ts
- src/app/shared/store/user.state.ts
- src/app/shell/personal-cabinet/applications/applications.component.html
- src/app/shell/personal-cabinet/applications/applications.component.scss
- src/app/shell/personal-cabinet/applications/applications.component.ts
- src/app/shell/personal-cabinet/provider/provider-org-info/provider-org-info.component.html
- src/app/shell/personal-cabinet/provider/provider-org-info/provider-org-info.component.scss
Hooked up Update/Application (statuses approved, rejected)
> Application status changing

- src/app/shared/components/child-card/child-card.component.html
- src/app/shared/components/child-card/child-card.component.scss
- src/app/shared/components/child-card/child-card.component.spec.ts
- src/app/shared/components/workshop-card/workshop-card.component.html
- src/app/shared/styles/cards.scss
> fixed bug workshop card position 

- src/app/shared/enum/messageBar.ts
- src/app/shared/models/rating.ts
- src/app/shared/store/user.actions.ts
- src/app/shared/store/user.state.ts
- src/app/shell/personal-cabinet/provider/provider-org-info/provider-org-info.component.html
- src/app/shell/workshop-details/side-menu/actions/actions.component.html
- src/app/shell/workshop-details/side-menu/actions/actions.component.ts
- src/app/shell/workshop-details/side-menu/side-menu.component.html
- src/app/shell/workshop-details/side-menu/side-menu.component.spec.ts
- src/app/shell/workshop-details/side-menu/side-menu.component.ts
- src/app/shell/workshop-details/workshop-details.component.html
- src/app/shell/workshop-details/workshop-details.component.spec.ts
- src/app/shell/workshop-details/workshop-details.component.ts
- src/app/shell/workshop-details/workshop-page/reviews/reviews.component.html
- src/app/shell/workshop-details/workshop-page/reviews/reviews.component.scss
- src/app/shell/workshop-details/workshop-page/reviews/reviews.component.spec.ts
- src/app/shell/workshop-details/workshop-page/reviews/reviews.component.ts
- src/app/shell/workshop-details/workshop-page/workshop-page.component.html
- src/app/shell/workshop-details/workshop-page/workshop-page.component.spec.ts
- src/app/shell/workshop-details/workshop-page/workshop-page.component.ts
If the role is provider, so rating button so not displayed.
If the user is not logged in, so on click it redirects to login page.
Added users' names and their rate as stars. At the new rate, the actual rate of the workshop is updated.
> Rating final update

- src/app/shared/components/city-autocomplete/city-autocomplete.component.html
- src/app/shared/components/city-autocomplete/city-autocomplete.component.scss
- src/app/shared/components/city-autocomplete/city-autocomplete.component.spec.ts
- src/app/shared/components/city-autocomplete/city-autocomplete.component.ts
- src/app/shared/components/city-confirmation/city-confirmation.component.html
- src/app/shared/components/city-confirmation/city-confirmation.component.scss
- src/app/shared/components/city-confirmation/city-confirmation.component.spec.ts
- src/app/shared/components/city-confirmation/city-confirmation.component.ts
- src/app/shared/components/full-search-bar/full-search-bar.component.ts
- src/app/shared/services/geolocation/geolocation.service.ts
- src/app/shared/shared.module.ts
- src/app/shared/store/filter.actions.ts
- src/app/shared/store/filter.state.ts
- src/app/shell/shell.component.ts
> created popup for confirmation users city

- src/app/shared/components/city-autocomplete/city-autocomplete.component.ts
- src/app/shared/components/filters-list/city-filter/city-filter.component.html
- src/app/shared/components/filters-list/city-filter/city-filter.component.spec.ts
- src/app/shared/components/filters-list/city-filter/city-filter.component.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-address/create-address.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-address/create-address.component.scss
- src/app/shell/personal-cabinet/provider/create-workshop/create-address/create-address.component.spec.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-address/create-address.component.ts
> added autocomplete

- src/app/shared/components/category-select/category-select.component.html
- src/app/shared/components/category-select/category-select.component.scss
- src/app/shared/components/category-select/category-select.component.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-address/create-address.component.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.html
1. The user can see the full list of options.
2. If the user clears the input, then the following dropdowns disappear + selected values reset.
3. If the user change option from the previous dropdown, the following  dropdowns disappear + selected values reset;
4. If the user starts typing values to the input and the filtering process begins, on the new dropdown click the user can see the whole list of options again. 
5. Added labels for departments and classes dropdowns.
> Categories

- src/app/shell/about/about.component.html
- src/app/shell/about/about.component.scss
- src/app/shell/personal-cabinet/applications/application-card/application-card.component.scss
> styles on the page About

- src/app/footer/footer.component.ts
> fixed snackBur position on the top

- src/app/header/header.component.html
- src/app/shared/components/category-card/category-card.component.html
- src/app/shared/components/category-card/category-card.component.scss
- src/app/shared/components/category-card/category-card.component.spec.ts
- src/app/shared/components/workshop-card/workshop-card.component.html
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.html
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.scss
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
- src/app/shell/personal-cabinet/parent/favorite-workshops/favorite-workshops.component.html
- src/app/shell/personal-cabinet/personal-cabinet.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.ts
- src/app/shell/result/result.component.ts
- src/app/shell/result/workshop-cards-list/workshop-cards-list.component.html
- src/app/shell/result/workshop-cards-list/workshop-cards-list.component.ts
- src/app/shell/workshop-details/side-menu/actions/actions.component.html
- src/app/shell/workshop-details/side-menu/actions/actions.component.scss
- src/app/shell/workshop-details/side-menu/actions/actions.component.spec.ts
- src/app/shell/workshop-details/side-menu/contacts/contacts.component.scss
- src/app/shell/workshop-details/side-menu/side-menu.component.html
- src/app/shell/workshop-details/workshop-page/workshop-page.component.html
1. Fixed create-application ts (removed edit mode)
2. Functionality for the second release is hidden
> Functionality for the second release

- src/app/shared/components/workshop-card/workshop-card.component.html
- src/app/shared/styles/cards.scss
- src/app/shell/main/main.component.html
- src/app/shell/main/main.component.scss
- src/app/shell/main/main.component.ts
> Fix position of workshops on the main page

- src/app/shared/components/workshop-card/workshop-card.component.html
- src/app/shared/services/workshops/user-workshop/user-workshop.service.ts
- src/app/shared/store/user.state.ts
- src/app/shell/personal-cabinet/cabinet-data/cabinet-data.component.ts
- src/app/shell/workshop-details/workshop-details.component.ts
- src/app/shell/workshop-details/workshop-page/all-provider-workshops/all-provider-workshops.component.ts
- src/app/shell/workshop-details/workshop-page/workshop-page.component.ts
Updated Workshop Card model according to the new response from the back-end
> Workshop card

- src/app/shared/components/filters-list/working-hours/working-hours.component.html
- src/app/shared/components/filters-list/working-hours/working-hours.component.scss
- src/app/shared/components/filters-list/working-hours/working-hours.component.spec.ts
- src/app/shared/components/filters-list/working-hours/working-hours.component.ts
Added possibility to reset start/end Time for workshop-filtering. Added possibility to add only endTime
> Feature/#574add possibilty to reset end/start time

- src/app/shared/components/filters-list/filters-list.component.html
- src/app/shared/components/filters-list/filters-list.component.scss
- src/app/shared/components/filters-list/filters-list.component.spec.ts
- src/app/shell/result/result.component.scss
- src/environments/environment.ts
> Restyle 'reset filters' button #623

- src/app/shared/components/filters-list/working-hours/working-hours.component.ts
- src/app/shared/components/workshop-card/workshop-card.component.html
- src/app/shared/components/workshop-card/workshop-card.component.scss
- src/app/shared/components/workshop-card/workshop-card.component.ts
- src/app/shared/store/user.state.ts
- src/app/shared/styles/cards.scss
- src/app/shell/personal-cabinet/cabinet-data/cabinet-data.component.ts
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.scss
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
- src/app/shell/personal-cabinet/workshops/workshops.component.html
- src/app/shell/personal-cabinet/workshops/workshops.component.spec.ts
- src/app/shell/personal-cabinet/workshops/workshops.component.ts
View for provider cabinet is updated. Workshop card display the amount of pending application for this workshop.
> Provider workshop card

- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/shared/components/filters-list/searchbar/searchbar.component.html
- src/app/shared/components/filters-list/searchbar/searchbar.component.scss
- src/app/shared/components/full-search-bar/full-search-bar.component.html
- src/app/shared/components/full-search-bar/full-search-bar.component.scss
- src/app/shell/all-categories/all-categories.component.html
- src/app/shell/all-categories/all-categories.component.scss
- src/app/shell/result/result.component.scss
Search field's size has been fixed as according to the design.
User name's font-size has been fixed as  the same font-size as other navigation titles in header-section
> Main page style fix/#646/makeev

- src/app/shared/styles/side-menu-cards.scss
- src/app/shell/workshop-details/side-menu/side-menu.component.html
- src/app/shell/workshop-details/side-menu/side-menu.component.spec.ts
- src/app/shell/workshop-details/side-menu/side-menu.component.ts
- src/app/shell/workshop-details/workshop-details.component.html
- src/app/shell/workshop-details/workshop-details.component.spec.ts
- src/app/shell/workshop-details/workshop-details.component.ts
> mobile view for side-menu action & contacts blocks

- src/app/shared/components/city-autocomplete/city-autocomplete.component.scss
- src/app/shared/components/filters-list/city-filter/city-filter.component.html
- src/app/shared/components/filters-list/working-hours/working-hours.component.scss
- src/app/shell/all-categories/all-categories.component.scss
- src/app/shell/result/result.component.scss
> fixed styles according to design

- src/app/shared/components/sidenav/sidenav.component.html
- src/app/shared/components/sidenav/sidenav.component.scss
Add Home route to burger menu in mobile view
> Home route

- src/app/shell/result/result.component.html
- src/app/shell/result/result.component.ts
> hided ordering dropdown on map view

- src/app/app.component.html
- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/header/header.component.ts
- src/app/shared/components/navigation-mobile-bar/navigation-mobile-bar.component.html
- src/app/shared/components/navigation-mobile-bar/navigation-mobile-bar.component.ts
- src/app/shared/components/workshop-card/workshop-card.component.html
- src/app/shell/main/main.component.html
- src/app/shell/main/main.component.scss
- src/app/shell/main/main.component.ts
- src/app/shell/result/workshop-map-view-list/workshop-map-view-list.component.ts
style fix on main page (font size according to design)
> Fix error: NG0100 & style fix on main page mobile view

- src/app/shared/components/category-select/category-select.component.html
- src/app/shared/components/category-select/category-select.component.scss
Оновлені стилі компонета category-select а саме dropdown menu.
Компонент використовується в редагуванні гуртка таба "Опис".
> feat: update dropdown element styles

- src/app/shell/personal-cabinet/parent/create-child/create-child.component.html
fix wrong routing on canlcel button create-child
> fix routing on cancel button

- .gitignore
- src/app/shared/components/validation-hint-for-input/validation-hint-for-input.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-address/create-address.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-address/create-address.component.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-workshop.component.ts
PR for bug: 
https://github.com/ita-social-projects/OoS-Frontend/issues/734
> #734: [Create workshop] - error If  or - char in the address

- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.ts
Set course price to 0 for a newly created free workshop
https://github.com/ita-social-projects/OoS-Frontend/issues/754
> add relevant course price to payload if user creates free workshop

- src/app/shared/components/workshop-card/workshop-card.component.ts
https://github.com/ita-social-projects/OoS-Frontend/issues/757
> fix pending applications count shown on workshop card

- src/app/shared/components/working-hours-form/working-hours-form.component.scss
https://github.com/ita-social-projects/OoS-Frontend/issues/763
> fix timepicker buttons layout for mobile view

- src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
[Providers cabinet - applications] Error on hover on Child name #755
> Error-on-hover-on-Child-name

- src/app/shared/utils/utils.ts
> #782 Child age should not be negative 

- src/app/shared/components/image-carousel/image-carousel.component.html
- src/app/shared/components/image-carousel/image-carousel.component.spec.ts
- src/app/shared/components/image-carousel/image-carousel.component.ts
- src/app/shared/models/carousel.model.ts
- src/app/shared/shared.module.ts
- src/app/shell/workshop-details/workshop-details.module.ts
- src/app/shell/workshop-details/workshop-page/workshop-page.component.html
- src/app/shell/workshop-details/workshop-page/workshop-page.component.ts
https://github.com/ita-social-projects/OoS-Frontend/issues/777
Add carousel component to shared module
Set transform style property of dynamically created div (that wraps all loaded images) to 'none' when onChange hook of image-carousel component fires to make newly loaded image(-s) sit in right place. Also set dotsArr property of Carousel component to fit actual image arr length
> Fix/upload relevant images#777

- src/app/shell/personal-cabinet/applications/applications.component.scss
issue: https://github.com/ita-social-projects/OoS-Frontend/issues/779
> fix application dropdown position

- src/app/shared/services/workshops/user-workshop/user-workshop.service.ts
> onDelete-Workshop-use-v2

- src/app/header/header.component.html
- src/app/shared/components/sidenav/sidenav.component.html
- src/app/shell/admin-tools/admin-tools.component.html
issue: https://github.com/ita-social-projects/OoS-Frontend/issues/792
Rename tab "надавачі" to "заклади",
remove "Повідомлення" tab,
remove "Налаштування" menu item from drop-down
> [Admin] Update layout according to mockups

- src/app/shared/constants/regex-constants.ts
The issue https://github.com/ita-social-projects/OoS-Frontend/issues/802
> [Create-Workshop] Map - fix validation

- src/app/shared/components/sidenav/sidenav.component.scss
> fix z-index of side menu on mobile view

- src/app/shared/components/stars/stars.component.scss
- src/app/shared/styles/create-form.scss
- src/app/shared/styles/toggle-button.scss
fix bgcolor of toggled buttons and size of 'price per lesson-month' button in create workshop
issue: https://github.com/ita-social-projects/OoS-Frontend/issues/799
I found out that commenting out some css properties works well for this task, but that properties are closely related to different toggle buttons throughout the application, so I tried to check every single page/form creation and haven't found any other unwanted changes in buttons appearance but to be safe I haven't deleted them, just commented out for now
> fix bgcolor and size of toggled buttons 

- src/app/header/header.component.scss
> #527 bold in safari

- src/app/shell/result/ordering/ordering.component.html
- src/app/shell/result/result.component.ts
issue: https://github.com/ita-social-projects/OoS-Backend/issues/529
Fix actions on Back and Forward browser buttons on result page
> [Functional] On browser return action (chrome "return" button click) count of workshops remain not changed #532

- src/app/header/header.component.scss
It appeared when progress bar was being shown
Also fixed progress bar position on mobile view
> fix horizontal scroll 

- src/app/shared/components/workshop-card/workshop-card.component.html
- src/app/shared/components/workshop-card/workshop-card.component.ts
- src/app/shared/enum/provider.ts
- src/app/shared/models/provider.model.ts
- src/app/shared/models/workshop.model.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
1. Update ownership type and enum OwnershipTypeUkr
2. fix displaying ownership field according to new ownership type:
> Update ownership type

- src/app/shell/admin-tools/platform/platform.component.scss
> chng style of Edit button bold in admin cabinet

- src/app/shell/personal-cabinet/parent/create-application/create-application.component.html
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.spec.ts
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
Issue: https://github.com/ita-social-projects/OoS-Frontend/issues/807
> Submit button should be disabled until all three checkboxes get checked

- src/app/shared/components/workshop-card/workshop-card.component.scss
> #832 fix button positioning

- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
The task https://github.com/ita-social-projects/OoS-Frontend/issues/820
> [Provider-details] fix dropdown placeholder

- src/app/shared/styles/create-form-wrapper.scss
> Fix the width #828

- src/app/shell/admin-tools/admin-tools.component.html
- src/app/shell/personal-cabinet/provider/provider-org-info/provider-org-info.component.html
add condition for website in provider cabinet
> No info no display

- src/app/shell/workshop-details/workshop-page/reviews/reviews.component.ts
An error in console showed up if the user role was 'undefined' or 'Provider'
> fix undefined for parent.id in Review component

- src/app/shell/workshop-details/side-menu/actions/actions.component.html
- src/app/shell/workshop-details/side-menu/side-menu.component.html
Issue: https://github.com/ita-social-projects/OoS-Frontend/issues/833
> Hide action card for admin role

- src/app/shared/components/confirmation-modal-window/confirmation-modal-window.component.html
- src/app/shared/enum/modal-confirmation.ts
Issue: https://github.com/ita-social-projects/OoS-Frontend/issues/848
> fix modal window for delete workshop confirmation

- src/app/shell/personal-cabinet/parent/create-child/child-form/child-form.component.html
- src/app/shell/personal-cabinet/parent/create-child/child-form/child-form.component.spec.ts
- src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
[Edit child] 'Місце проживання' and 'Серія та номер свідоцтва про народження' fields are not displayed #857
> Edit child 857

- src/app/shared/styles/buttons.scss
- src/app/shell/personal-cabinet/parent/create-child/create-child.component.html
[Add child] The 'Додати ще одну дитину' button stays enabled when mandatory fields are empty https://github.com/ita-social-projects/OoS-Frontend/issues/861
> disable button if form is invalid

- src/app/shared/components/message-bar/message-bar.component.scss
- src/app/shared/store/user.state.ts
[Add child] Incorrect message is displayed when a new child is created #858
> fix message when add new child

- src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.html
Issue: https://github.com/ita-social-projects/OoS-Frontend/issues/871
> Add asterisk to required field in Create Workshop

- src/app/shared/enum/role.ts
- src/app/shell/personal-cabinet/personal-cabinet.component.html
Issue: https://github.com/ita-social-projects/OoS-Backend/issues/537, https://github.com/ita-social-projects/OoS-Backend/issues/536
> fix tab names

- src/app/shared/constants/regex-constants.ts
- src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
Issue: https://github.com/ita-social-projects/OoS-Frontend/issues/850
> [Add child] Fix input validation for name fields (no white-spaces allowed)

- src/app/shared/components/workshop-card/workshop-card.component.html
- src/app/shared/styles/create-form-wrapper.scss
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.html
Issue: https://github.com/ita-social-projects/OoS-Frontend/issues/888
Display and hide appropriate fields on workshop card on different views (Main page - result map view - create application view) according to design
> Arrange workshop card fields in Create App and Main page (map view)

- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.spec.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.ts
Task https://github.com/ita-social-projects/OoS-Frontend/issues/908
add min/max date for the datepicker
add min max notification
add incorrect value notification
add keyfilter for the date format
> ['Редагування закладу' page] Incorrect behavior is displayed when entering invalid data in the 'Дата народження керівника' field

- src/app/shared/store/user.actions.ts
- src/app/shared/store/user.state.ts
- src/app/shell/workshop-details/workshop-details.component.ts
Issue: https://github.com/ita-social-projects/OoS-Frontend/issues/855
> Error if workshop deleted

- src/app/footer/footer.component.html
Task https://github.com/ita-social-projects/OoS-Frontend/issues/942
> [Footer] The English localization of the ‘SoftServe’ website appears when clicking the ‘SoftServe’ logo in the footer

- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
['Інформація про заклад' section] Spelling mistake exists in the name of the field #904
> ['Інформація про заклад' section] Spelling mistake exists in the name of the field #904

- src/app/shared/constants/regex-constants.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.ts
['Редагування закладу' page] Incorrect validation of the 'ІПН' field with correct data #903
> ['Редагування закладу' page] Incorrect validation of the 'ІПН' field with correct data #903

- src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.html
['Редагування закладу' page] Incorrect title and text at the top of the page #906
> ['Редагування закладу' page] Incorrect title and text at the top of the page #906

- src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.html
- src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-provider.guard.spec.ts
['Редагування закладу' page] 'Далі' button stays enabled when mandatory field is empty #905
> ['Редагування закладу' page] 'Далі' button stays enabled when mandatory field is empty #905

- src/app/shared/components/filters-list/searchbar/searchbar.component.html
[Search field] The max 200 chars can be entered into the ‘Search’ field #913
> [Search field] The max 200 chars can be entered into the ‘Search’ field #913

- src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-workshop.component.html
['Редагування закладу' page] Incorrect action after pressing the 'Скасувати' button #915
> ['Редагування закладу' page] Incorrect action after pressing the 'Скасувати' button #915

- src/app/shared/components/child-card/child-card.component.html
- src/app/shared/components/image-form-control/image-form-control.component.ts
- src/app/shared/components/workshop-card/workshop-card.component.html
- src/app/shared/components/workshop-card/workshop-card.component.scss
- src/app/shared/components/workshop-card/workshop-card.component.ts
- src/app/shared/models/workshop.model.ts
- src/app/shared/services/workshops/user-workshop/user-workshop.service.ts
- src/app/shared/styles/cards.scss
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-workshop.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-workshop.component.spec.ts
- src/styles.scss
add functionality to manage workshop cover image, fix styles according to design on main page (list and map view) and create app page
> Workshop cover image

- src/app/shared/components/users-list/users-list.component.html
- src/app/shared/components/users-list/users-list.component.ts
- src/app/shared/enum/no-results.ts
- src/app/shared/store/user.state.ts
- src/app/shell/personal-cabinet/provider-admins/provider-admins.component.html
- src/app/shell/personal-cabinet/provider-admins/provider-admins.component.spec.ts
- src/app/shell/personal-cabinet/provider-admins/provider-admins.component.ts
Task https://github.com/ita-social-projects/OoS-Frontend/issues/992
> [Service provider] 'Адміністрування' tab - add no results section

- src/app/shared/components/workshop-checkbox-dropdown/workshop-checkbox-dropdown.component.html
- src/app/shared/components/workshop-checkbox-dropdown/workshop-checkbox-dropdown.component.ts
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.html
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.scss
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.spec.ts
Task https://github.com/ita-social-projects/OoS-Frontend/issues/994
> [Service provider] 'Адміністрування' tab - fix dropdown

- src/app/shell/personal-cabinet/parent/create-child/create-child.component.html
[Add child] The 'ЗБЕРЕГТИ' button stays enabled when mandatory fields are empty #965
> [Add child] The 'ЗБЕРЕГТИ' button stays enabled when mandatory fields are empty #965

- src/app/shared/components/sidenav/sidenav.component.html
- src/app/shared/components/users-list/users-list.component.html
- src/app/shell/personal-cabinet/provider-admins/provider-admins.component.scss
Task https://github.com/ita-social-projects/OoS-Frontend/issues/993
> [Service provider] 'Адміністрування' tab - mobile view fix

- src/app/shared/components/sidenav/sidenav.component.html
- src/app/shared/components/users-list/users-list.component.html
- src/app/shared/store/user.state.ts
- src/app/shell/personal-cabinet/provider-admins/provider-admins.component.html
- src/app/shell/personal-cabinet/provider-admins/provider-admins.component.scss
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.html
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.scss
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.spec.ts
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.ts
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1011
> [Service provider] 'Адміністрування' tab - registration stepper

- src/app/header/header.component.ts
Check if the middle name is empty then remove the second dot if yes.
> [Header] Check if middle name is empty

- src/app/shared/components/filters-list/filters-list.component.html
- src/app/shared/components/full-search-bar/full-search-bar.component.scss
- src/app/shell/all-categories/all-categories.component.scss
- src/app/shell/result/result.component.scss
1. search bar width fix
2. search bar mobile positioning fix
3. letter case fix
related issues:
https://github.com/ita-social-projects/OoS-Frontend/issues/973
https://github.com/ita-social-projects/OoS-Frontend/issues/928
https://github.com/ita-social-projects/OoS-Frontend/issues/927
> search field fix

- src/app/shared/constants/regex-constants.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.ts
['Редагування закладу' page] Incorrect behavior is displayed when entering invalid data in the 'Веб сайт', 'Facebook', 'Instagram' fields #920
> ['Редагування закладу' page] Incorrect behavior is displayed when entering invalid data in the 'Веб сайт', 'Facebook', 'Instagram' fields #920

- src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.html
Task https://github.com/ita-social-projects/OoS-Frontend/issues/924
> ['Редагування закладу' page] Buttons are not displayed correctly

- src/app/shared/constants/regex-constants.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.ts
['Редагування закладу' page] Incorrect behavior is displayed when entering invalid data in the 'ПІБ керівника', 'Засновник' fields #907
> ['Редагування закладу' page] Incorrect behavior is displayed when entering invalid data in the 'ПІБ керівника', 'Засновник' fields #907

- cloudbuild.yaml
use older buildpack version
add layer cache
fix removing old revisions
> fix continuous delivery

- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
> Mandatory fields

- src/app/shared/constants/regex-constants.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.html
['Редагування закладу' page] Incorrect behavior is displayed when entering invalid data in the 'Вулиця', 'Будинок' fields #918
> ['Редагування закладу' page] Incorrect behavior is displayed when entering invalid data in the 'Вулиця', 'Будинок' fields #918

- src/app/shell/workshop-details/side-menu/contacts/contacts.component.html
[Workshop page] Indent of the text from the logo is different from the rest in unit "Контакти" #933
> [Workshop page] Indent of the text from the logo is different from the rest in unit "Контакти" #933

- src/app/shared/pipes/phone-transform.pipe.ts
- src/app/shell/personal-cabinet/user-config/user-config.component.html
- src/app/shell/personal-cabinet/user-config/user-config.component.spec.ts
- src/app/shell/workshop-details/side-menu/contacts/contacts.component.html
[UI] No indentation in phone number #979
> [UI] No indentation in phone number #979

- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
- src/app/shell/personal-cabinet/provider/provider-org-info/provider-org-info.component.html
https://github.com/ita-social-projects/OoS-Frontend/issues/1050
> ['Редагування закладу' page] field name "ЕДРПОУ" or "ІПН"

- src/app/shell/result/workshop-cards-list/workshop-cards-list.component.html
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1058
> [Map] - while loading to not display pagination

- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.html
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1062
> [Create administrator] - stepper fix

- src/app/shared/components/child-card/child-card.component.scss
[Child-card] - workshop list fix #1064
> [Child-card] - workshop list fix #1064

- src/app/shell/admin-tools/platform/platform.component.html
- src/app/shell/admin-tools/platform/platform.component.scss
Edit button admin personal cabinet
> Edit button admin personal cabinet style fix

- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
- src/app/shell/personal-cabinet/provider/provider-org-info/provider-org-info.component.html
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1090
> ['Редагування закладу' page] 'ЄДРПОУ' field

- src/app/shared/components/reject-modal-window/reject-modal-window.component.scss
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1091
> [Reject application] - reject application modal window style #1091 

- src/app/shell/personal-cabinet/personal-cabinet.component.html
> Route Admin

- src/app/shared/components/validation-hint-for-input/validation-hint-for-input.component.html
- src/app/shared/services/applications/application.service.ts
- src/app/shared/store/user.actions.ts
- src/app/shared/store/user.state.ts
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.html
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.scss
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
warning message and naming
https://github.com/ita-social-projects/OoS-Frontend/pull/1167#discussion_r872499814
> Warning message

- src/app/shell/personal-cabinet/personal-cabinet.component.html
- src/app/shell/personal-cabinet/provider-admins/provider-admins.component.ts
Fix loading users fix if default state is null
> [Provider admins] loading users fix

- src/app/shell/personal-cabinet/parent/create-application/create-application.component.html
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1142
> [Applying for a workshop] Inconsistency of the checkboxes on the 'Application' page with the design

- src/app/shared/components/teacher-card/teacher-card.component.scss
- src/app/shell/details/information-page/workshop-about/workshop-about.component.scss
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1150
> [Workshop page] No line breaking in text fields

- src/app/shared/components/working-hours-form-wrapper/working-hours-form-wrapper.component.html
- src/app/shared/components/working-hours-form-wrapper/working-hours-form-wrapper.component.scss
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1145
> [Create workshop] The alignment of ‘Дні/Години’ buttons is broken on the ‘Про гурток’ section of the ‘Новий гурток’ page

- src/app/shared/components/workshop-card/workshop-card.component.scss
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.scss
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1141
> [Applying for a workshop] Inconsistency of the 'Application' page with the design

- src/app/shared/components/teacher-card/teacher-card.component.scss
- src/app/shell/details/information-page/workshop-about/workshop-about.component.scss
- src/app/shell/details/side-menu/contacts/contacts.component.scss
1) Task https://github.com/ita-social-projects/OoS-Frontend/issues/1182
2) mat-icon vertical align
> [Workshop details] - fix length of link in workshop details

- src/app/header/header.component.html
- src/app/header/header.component.ts
- src/app/shell/admin-tools/admin-tools-routing.module.ts
- src/app/shell/admin-tools/admin-tools.component.html
- src/app/shell/admin-tools/data/data-routing.module.ts
1) data module routing
2) header loading state
> [Tech admin] data module routing

- src/app/shell/personal-cabinet/parent/create-application/create-application.component.html
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1133
> [Applying for a workshop] The 'Скасувати' button doesn't cancel the applying process

- src/app/shared/components/person-card/person-card.component.html
- src/app/shared/components/person-card/person-card.component.spec.ts
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1141
3 point about phone number
> [Applying for a workshop] Inconsistency of the 'Application' page with the design (phone number)

- src/app/shared/models/workshop.model.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.ts
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1124
> [Create workshop] The ‘Директор’ field, which is absent on the design, appears when creating a workshop

- src/app/shell/admin-tools/data/provider-list/provider-list.component.html
> [Admin-tools] - remove add provider button in administration cabinet #1212

- src/app/shared/components/filters-list/age-filter/age-filter.component.html
- src/app/shared/components/filters-list/filters-list.component.html
- src/app/shared/components/working-hours-form-wrapper/working-hours-form/working-hours-form.component.html
linked issues: 
https://github.com/ita-social-projects/OoS-Frontend/issues/1228
https://github.com/ita-social-projects/OoS-Frontend/issues/928
> [Working Hours] - fix broken alignment of working hours #1228

- src/app/shared/components/category-card/category-card.component.html
- src/app/shared/components/category-card/category-card.component.scss
- src/app/shared/components/category-card/category-card.component.ts
- src/app/shared/store/admin.state.ts
https://github.com/ita-social-projects/OoS-Frontend/issues/1248
> [Create Direction] - remove routing when you click on delete/edit icon on category-card #1248

- src/app/shell/admin-tools/platform/directions/create-direction/add-class-form/new-class-form/new-class-form.component.html
- src/app/shell/admin-tools/platform/directions/create-direction/add-department-form/add-department-form.component.html
- src/app/shell/admin-tools/platform/directions/create-direction/add-direction-form/add-direction-form.component.html
[Create Direction] - add validation hint for create direction #1236
> [Create Direction] - add validation hint for create direction #1236

- src/app/shell/personal-cabinet/parent/create-child/create-child.component.html
- src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
Linked issue: https://github.com/ita-social-projects/OoS-Frontend/issues/1260
> [Create Child] - social groups fix

- src/app/shell/personal-cabinet/parent/create-application/create-application.component.html
linked issue https://github.com/ita-social-projects/OoS-Frontend/issues/1140
> Fixed button letter. Lowercase changed to uppercase. (#1140)

- src/app/shared/constants/constants.ts
- src/app/shell/admin-tools/platform/directions/create-direction/add-class-form/add-class-form.component.ts
- src/app/shell/admin-tools/platform/directions/create-direction/add-class-form/classes-check-box-list/classes-check-box-list.component.ts
- src/app/shell/admin-tools/platform/directions/create-direction/add-department-form/add-department-form.component.ts
- src/app/shell/admin-tools/platform/directions/create-direction/add-direction-form/add-direction-form.component.ts
- src/app/shell/admin-tools/platform/directions/directions.component.ts
- src/app/shell/details/information-page/reviews/reviews.component.ts
- src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts
- src/app/shell/personal-cabinet/create.guard.ts
- src/app/shell/personal-cabinet/parent/children/children.component.ts
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
- src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
- src/app/shell/personal-cabinet/provider-admins/provider-admins.component.ts
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-teacher/create-teacher.component.ts
- src/app/shell/personal-cabinet/workshops/workshops.component.ts
The modal window size was moved to constants
> Modal Window Constant - small modal window

- src/app/shell/result/result.component.html
- src/app/shell/result/workshop-map-view-list/workshop-map-view-list.component.html
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1265
> [Result] - fix view

- src/app/shell/personal-cabinet/user-config/user-config-edit/user-config-edit.component.html
Follow link https://github.com/ita-social-projects/OoS-Frontend/issues/1268
> Added star for a required field По-батькові. (#1268)

- src/app/shared/components/provider-info/provider-info.component.scss
- src/app/shell/info/info.component.scss
- src/app/shell/personal-cabinet/provider/provider-org-info/provider-org-info.component.scss
related issue: https://github.com/ita-social-projects/OoS-Frontend/issues/1222
> [Mobile View] - style fix

- src/app/shared/styles/working-hours.scss
- src/app/shell/details/details-tabs/workshop-about/workshop-about.component.html
- src/app/shell/details/details-tabs/workshop-about/workshop-about.component.scss
[Workshop-details] - restyle working hours view #1269
> [Workshop-details] - restyle working hours view #1269

- src/app/shell/personal-cabinet/parent/create-child/child-form/child-form.component.html
- src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-teacher/create-teacher.component.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1309
> Oi#1309 Displayed a modal confirmation window when deleting teachers

- src/app/shared/components/filters-list/filters-list.component.ts
- src/app/shared/store/navigation.actions.ts
- src/app/shared/store/navigation.state.ts
- src/app/shell/result/result.component.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1311
> The fixed -  filter doesn't open by default

- src/app/shared/components/teacher-card/teacher-card.component.html
- src/app/shared/components/teacher-card/teacher-card.component.ts
- src/app/shared/models/teacher.model.ts
- src/app/shared/utils/utils.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-teacher/create-teacher.component.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-teacher/teacher-form/teacher-form.component.html
Changer  avatarImage -> coverImage and avatarImageId -> coverImageId
> Updated Teacher avatarImage and avatarImageId

- src/app/shared/components/paginator/paginator.component.html
- src/app/shared/components/paginator/paginator.component.ts
> [Paginator dropdown] - highlight current selected value #1271

- src/app/shared/components/image-cropper-modal/image-cropper-modal.component.html
- src/app/shared/components/image-cropper-modal/image-cropper-modal.component.scss
- src/app/shared/components/image-cropper-modal/image-cropper-modal.component.ts
- src/app/shared/components/image-form-control/image-form-control.component.html
- src/app/shared/components/image-form-control/image-form-control.component.ts
Task https://github.com/ita-social-projects/OoS-Frontend/issues/1344
> [Image cropper] Fix bugs and height cropper

- src/app/header/header.component.html
- src/app/header/header.component.ts
- src/app/shared/components/filters-list/filters-list.component.ts
- src/app/shared/models/workshop.model.ts
- src/app/shared/store/filter.actions.ts
- src/app/shared/store/filter.state.ts
- src/app/shell/details/details-tabs/reviews/reviews.component.scss
- src/app/shell/result/ordering/ordering.component.html
- src/app/shell/result/ordering/ordering.component.scss
- src/app/shell/result/result.component.ts
- src/app/shell/result/workshop-cards-list/workshop-cards-list.component.html
- src/app/shell/result/workshop-cards-list/workshop-cards-list.component.spec.ts
- src/app/shell/result/workshop-cards-list/workshop-cards-list.component.ts
- src/app/shell/result/workshop-map-view-list/workshop-map-view-list.component.ts
Removed doubled requests for city, workshops are not displayed until the loading is finished
> [Result page] - fix filter loading, removed double requests

- src/app/shared/components/image-cropper-modal/image-cropper-modal.component.html
- src/app/shared/components/image-cropper-modal/image-cropper-modal.component.ts
- src/app/shared/components/login/login.component.spec.ts
- src/app/shared/components/login/login.component.ts
- src/app/shared/shared.module.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-workshop.component.ts
- src/app/shell/shell-routing.module.ts
provide a component that will login the user initially
fix image cropping validation
> Image cropper/ Login

- src/app/shared/components/notifications/notifications.component.html
- src/app/shared/components/paginator/paginator.component.html
- src/app/shared/components/paginator/paginator.component.ts
- src/app/shared/constants/constants.ts
- src/app/shared/constants/regex-constants.ts
- src/app/shared/enum/navigation-bar.ts
- src/app/shared/enum/role.ts
- src/app/shell/personal-cabinet/parent/children/child-card/child-card.component.html
- src/app/shell/personal-cabinet/parent/children/child-card/child-card.component.spec.ts
- src/app/shell/personal-cabinet/parent/children/child-card/child-card.component.ts
- src/app/shell/personal-cabinet/parent/children/children.component.ts
remove child workshops - https://github.com/ita-social-projects/OoS-Frontend/issues/1480
change no-notifications text https://github.com/ita-social-projects/OoS-Frontend/issues/1481
change parent name tab - https://github.com/ita-social-projects/OoS-Frontend/issues/1479
address validation fix https://github.com/ita-social-projects/OoS-Frontend/issues/1401
https://github.com/ita-social-projects/OoS-Frontend/issues/1339
breadcrumbs https://github.com/ita-social-projects/OoS-Frontend/issues/1397
pagination https://github.com/ita-social-projects/OoS-Frontend/issues/1428
> Minor Bug Fixes

- src/app/header/header.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-workshop.component.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1495
> [Create Workshop] - remove userWorkshopService from the component, move that logic to the state

- src/app/shared/components/navigation-bar/navigation-bar.component.scss
#1568 
*Added properties for nav arrow alignment
> Fixed alignment for navigation bar arrows

- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/header/header.component.html
- src/app/header/header.component.scss
- src/app/header/header.component.spec.ts
- src/app/header/header.component.ts
- src/app/header/progress-bar/progress-bar.component.html
- src/app/header/progress-bar/progress-bar.component.scss
- src/app/header/progress-bar/progress-bar.component.spec.ts
- src/app/header/progress-bar/progress-bar.component.ts
- src/app/shared/services/geolocation/geolocation.service.ts
- src/app/shared/services/workshops/app-workshop/app-workshops.service.ts
- src/app/shared/store/filter.actions.ts
- src/app/shared/store/filter.state.ts
- src/app/shared/store/main-page.actions.ts
- src/app/shared/store/main-page.state.ts
- src/app/shared/store/meta-data.actions.ts
- src/app/shared/store/meta-data.state.ts
- src/app/shared/store/registration.state.ts
- src/app/shell/main/main.component.html
- src/app/shell/main/main.component.scss
- src/app/shell/main/main.component.ts
1. When a user is checking its registry - no website action is available
2. while top workshops are loading - no page hiding
3. When the Provider is not finally registered, no tab to navigate to personal cabinet
4. general improvments
> Main page loading

- src/app/shared/services/signalR/signal-r.service.ts
- src/app/shared/store/admin.state.ts
- src/app/shared/store/registration.state.ts
- src/app/shared/store/user.state.ts
- src/main.ts
#1592 
* removed all console.log commands from code
> Remove console.log from code

- src/app/footer/footer.component.scss
- src/app/shared/components/filters-list/city-filter/city-filter.component.scss
- src/app/shared/components/filters-list/full-search-bar/full-search-bar.component.scss
#1594 
*Fixed white bar on the right
*Fixed incorrect display city-confirmation modal window
> [Mobile-view] - main page, result-page

- src/app/shared/components/category-card/category-card.component.html
- src/app/shared/components/category-card/category-card.component.scss
- src/app/shared/components/category-card/category-card.component.spec.ts
- src/app/shared/components/category-card/category-card.component.ts
- src/app/shared/models/category.model.ts
- src/app/shared/services/directions/directions.service.ts
- src/app/shared/store/main-page.state.ts
- src/app/shell/main/main.component.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1604
And also fix bug: https://github.com/ita-social-projects/OoS-Frontend/issues/1112
> [TopDirections/ GetDirections] - display amount of workshops for every top direction

- src/app/shared/components/filters-list/searchbar/searchbar.component.ts
#1425 
* Added a command to clear the input when going to the main page
* Replaced SetSearchQueryValue command with GetFilteredWorkshops
( Due to the filtering call in the method that moves to the result page, I see no reason to call it again )
> Fixed broken search from main page

- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.html
#1610
* Removed maximum age limit for members
> Removed age limitation

- src/app/shared/constants/constants.ts
- src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.ts
#1616
* Set default value for social group without using constant
* Removed constant for social groups
* Added a new constant for institutionStatusId. Previously, the social group constant was used for this variable.
> Fixed adding child without social group

- src/app/shell/admin-tools/data/admins/admins.component.ts
- src/app/shell/admin-tools/data/provider-list/provider-list.component.ts
- src/app/shell/admin-tools/data/users/users.component.ts
- src/app/shell/admin-tools/platform/directions/directions.component.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1577
> [Bug] Search input is called on initialization

- src/app/shared/models/category.model.ts
- src/app/shared/services/directions/directions.service.ts
- src/app/shared/store/main-page.state.ts
- src/app/shell/main/main.component.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1627
> [GetTopDirections] - update request with city filtration

- src/app/shared/components/notifications/notifications-list/notifications-list.component.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1624
> [Notifications] Link in the notification leads to 404 page #1624

- src/app/header/header.component.html
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1606
> [Laws and regulations] - display laws and regulations on the main page #1606

- src/app/shared/directives/show-tooltip-if-truncated.directive.ts
- src/app/shell/details/details-tabs/achievements/achievement-card/achievement-card.component.html
- src/app/shell/details/details-tabs/achievements/achievement-card/achievement-card.component.spec.ts
- src/app/shell/details/details-tabs/achievements/achievement-card/achievement-card.component.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1613
> [Achievements] - add tooltip on achievement card, when the achievement title is not fully displayed

- src/app/shared/components/notifications/notifications-list/notifications-list.component.html
- src/app/shared/components/notifications/notifications-list/notifications-list.component.ts
- src/app/shared/enum/enumUA/workshop.ts
- src/app/shared/models/notifications.model.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1625
> [Notifications] - handle new type of notifications #1625

- src/app/shared/services/applications/application.service.ts
- src/app/shared/store/provider.actions.ts
- src/app/shared/store/provider.state.ts
- src/app/shared/styles/application-list.scss
- src/app/shell/personal-cabinet/provider/provider-applciations/provider-applciations.component.html
- src/app/shell/personal-cabinet/provider/provider-applciations/provider-applciations.component.ts
- src/app/shell/personal-cabinet/shared-cabinet/applications/application-card/application-card.component.ts
- src/app/shell/personal-cabinet/shared-cabinet/applications/application-card/info-status/info-status.component.ts
- src/app/shell/personal-cabinet/shared-cabinet/applications/applications.component.html
- src/app/shell/personal-cabinet/shared-cabinet/applications/applications.component.ts
Issue: https://github.com/ita-social-projects/OoS-Frontend/issues/1642
> [Application Block/Unblock] - status change refactoring, loading fix

- src/app/shared/components/notifications/notifications.component.scss
Fixed notification icon topbar AC #1657
> Fixed notification icon topbar AC#1657

- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1683
> [Create Provider/Debuty] Wrong navBarTitle 

- src/app/shared/store/provider.state.ts
- src/app/shared/store/registration.state.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.html
- src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.ts
- src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.html
- src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.spec.ts
1. image form control is hidden
2. save button is not available if checkboxes are not checked
3. after successful provider creation, the full menu bar is available
> [Create/Update provider] - form fix, image form control is hidden, validation form fix

- src/app/shell/admin-tools/data/history-log-table/history-log-table.component.html
- src/app/shell/admin-tools/data/history-log-table/history-log-table.component.ts
Changed short date pipe for data column #1665
> Changed short date pipe for data column #1665

- src/app/shared/components/provider-info/provider-info.component.html
- src/app/shared/components/provider-info/provider-info.component.scss
- src/app/shell/details/details-tabs/provider-about/provider-about.component.scss
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1659
> Fix title styling for provider information

- src/app/shared/components/message-bar/message-bar.component.html
- src/app/shared/components/message-bar/message-bar.component.scss
#1128
*Fixed text alignment
*Added class to lower by 1px
Before:
After:
> Fixed message display design

- src/app/shared/models/providerAdmin.model.ts
- src/app/shared/store/provider.state.ts
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.html
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1689
> [Add Assistant/admin] Not possible to create an assistant/admin (500 error)

- src/app/shared/constants/constants.ts
- src/app/shared/store/filter.state.ts
- src/app/shared/store/parent.state..ts
- src/app/shared/store/provider.state.ts
- src/app/shared/store/shared-user.state.ts
#1717 
* Created EMPTY_RESULT const
* Applied EMPTY_RESULT all over the code
> Moved the empty result to const

- src/app/shared/components/workshop-card/workshop-card.component.ts
- src/app/shared/enum/messageBar.ts
- src/app/shared/store/admin.state.ts
- src/app/shared/store/notifications.state.ts
- src/app/shared/store/parent.state..ts
- src/app/shared/store/provider.state.ts
- src/app/shared/store/registration.state.ts
- src/app/shared/store/shared-user.state.ts
- src/app/shell/details/side-menu/actions/actions.component.ts
#1715 
* Created enum 'messageText'
* Replaced literals with texts from enum
> move all message-bar messages to the enum

- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.html
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.scss
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.scss
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.scss
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1724
> [Create Workshop] fixed css, placeholder

- src/app/shared/components/filters-list/city-filter/city-filter.component.html
- src/app/shared/components/filters-list/city-filter/city-filter.component.scss
- src/app/shared/components/filters-list/city-filter/city-filter.component.spec.ts
- src/app/shared/components/filters-list/city-filter/city-filter.component.ts
- src/app/shared/services/geolocation/geolocation.service.ts
- src/app/shared/store/filter.actions.ts
- src/app/shared/store/filter.state.ts
- src/app/shell/shell.component.ts
#1733 
* Fixed cropped cross icon
* Removed wrapping of additional text about the city
* Fixed incorrectly working geolocation confirmation
> Issue#1733 city confirmation

- .eslintrc.json
- src/app/shared/components/map/map.component.scss
- src/app/shared/components/map/map.component.ts
- src/app/shared/models/filter-state.model.ts
- src/app/shared/services/workshops/app-workshop/app-workshops.service.ts
- src/app/shared/store/filter.actions.ts
- src/app/shared/store/filter.state.ts
- src/app/shell/admin-tools/data/directions-wrapper/directions-wrapper.component.spec.ts
- src/assets/icons/user_dot.svg
user-radius has been provided for map view
> user-radius has been provided for map view

- src/app/shared/components/map/map.component.ts
- src/app/shared/models/address.model.ts
- src/app/shared/models/geolocation.ts
- src/app/shared/services/geolocation/geocoder.service.ts
- src/app/shared/store/main-page.state.ts
- src/app/shell/personal-cabinet/provider/create-address-form/create-address-form.component.html
- src/app/shell/personal-cabinet/provider/create-address-form/create-address-form.component.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-workshop-address/create-workshop-address.component.ts
#1736 
* Removed a command that tried to access non-existent coordinates and crashed the function
* Removed interfaces that duplicate coordinate fields from the base interface
* Fixed removal of codeficatorid when clicking on an empty place on the map
* Fixed duplicate requests when user clicks on map
* Fixed display of a search error when an address is found
* Fixed a bug where coordinates were lost due to different field names
> Issue#1736 general issues map

- src/app/shared/directives/trim-value.directive.ts
#1745 
* Fixed a directive that triggered a request event
> Fixed a directive that triggered a request event

- .eslintrc.json
- .prettierignore
- .prettierrc.json
- package.json
- yarn.lock
Prettier has been added
EsLinter configuration has been changed for fix conflict
> #1742[Prettier]

- src/app/shared/enum/navigation-bar.ts
- src/app/shell/admin-tools/data/directions-wrapper/directions-wrapper.component.spec.ts
- src/app/shell/admin-tools/data/directions-wrapper/directions-wrapper.component.ts
- src/app/shell/admin-tools/data/directions-wrapper/directions/directions.component.ts
- src/app/shell/admin-tools/data/history-log/history-log.component.ts
1. added path for direction and history-log tabs
2. fixed removing nav path
related issue: https://github.com/ita-social-projects/OoS-Frontend/issues/1664
> Navigation bar - fixed navigation for admin-tools

- src/app/shared/components/filters-list/full-search-bar/full-search-bar.component.ts
- src/app/shared/components/filters-list/searchbar/searchbar.component.ts
fixed search bar, removed triggering double request on search init, fixed value saving flow to local storage
> [Search Bar] - removed double request triggering  on search init, fixed value saving flow to local storage

- src/app/shell/personal-cabinet/parent/favorite-workshops/favorite-workshops.component.html
- src/app/shell/personal-cabinet/parent/favorite-workshops/favorite-workshops.component.spec.ts
- src/app/shell/personal-cabinet/parent/favorite-workshops/favorite-workshops.component.ts
Follow the link: https://github.com/ita-social-projects/OoS-Frontend/issues/1787
> [Pagination] - items per page is missing for favorites workshops

- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
- src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.spec.ts
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/working-hours-form-wrapper/working-hours-form/working-hours-form.component.html
- src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/working-hours-form-wrapper/working-hours-form/working-hours-form.component.spec.ts
- src/app/shell/personal-cabinet/provider/provider.module.ts
#1843 
* Added translate pipe to places where was no translation
> Issue#1843 Fixed translate bugs

- src/app/shared/constants/constants.ts
- src/app/shell/details/details.component.ts
- src/app/shell/details/side-menu/actions/actions.component.html
- src/app/shell/details/side-menu/actions/actions.component.ts
- src/app/shell/personal-cabinet/parent/children/children.component.html
- src/app/shell/personal-cabinet/parent/children/children.component.ts
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.html
- src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
- src/app/shell/personal-cabinet/parent/create-child/child-form/child-form.component.html
- src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
- src/app/shell/personal-cabinet/provider/provider-workshops/provider-workshops.component.html
- src/app/shell/personal-cabinet/provider/provider-workshops/provider-workshops.component.ts
- src/app/shell/personal-cabinet/shared-cabinet/create-form/create-form.component.ts
- src/app/shell/personal-cabinet/shared-cabinet/messages/chat/chat.component.ts
- src/app/shell/shell-routing.module.ts
#1835 
* Added a new constant for modes
* Fixed 404 error for create-workshop and create-child by adding mode to parameter
* Removed unused fields and form controls
* Merged two routes redirecting to the same component into one
> Issue#1835 fix page loading on refresh

- src/app/shared/components/users-list/users-list.component.ts
- src/app/shell/admin-tools/data/admins/admins.component.html
- src/app/shell/admin-tools/data/admins/admins.component.ts
#1841 
* Template set for tabs admin-region and admin-otg
* Removed unused variable
> Issue#1841 no result wrap

- src/app/shared/services/applications/application.service.ts
- src/app/shared/services/children/children.service.ts
- src/app/shared/services/codeficator/codeficator.service.ts
- src/app/shared/services/directions/directions.service.ts
- src/app/shared/services/history-log/history-log.service.ts
- src/app/shared/services/institutions/institutions.service.ts
- src/app/shared/services/ministry-admin/ministry-admin.service.ts
- src/app/shared/services/provider-admins/provider-admin.service.ts
- src/app/shared/services/provider/provider.service.ts
- src/app/shared/services/rating/rating.service.ts
- src/app/shared/services/workshops/app-workshop/app-workshops.service.ts
#1829 
* Implemented chain setting for HttpParams
> Implemented chain setting for HttpParams

- src/app/shell/personal-cabinet/shared-cabinet/applications/applications.component.ts
#1864 
* Added redirect when changing address parameters
> [Personal-Cabinet] - No redirect on change #1864

- src/app/shared/components/notifications/notifications-list/notifications-list.component.html
- src/app/shared/components/notifications/notifications-list/notifications-list.component.scss
- src/styles.scss
#1865 
* Added read button blocking when notification(s) is already marked as read
* Added readAll/deleteAll buttons blocking when there are no unread notifications or no notifications
* Moved the arrow to the right and added hover links
* Fixed mobile view
> Issue#1865 notifications improvements

- src/app/shared/components/entity-checkbox-dropdown/entity-checkbox-dropdown.component.ts
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.html
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.ts
Label was changed; Button disable without workshops
> [ProviderAdmin/ProderDeputy] - on create/update workshop selection

- src/app/shared/components/map/map.component.ts
- src/app/shell/result/result.component.ts
- src/app/shell/result/workshop-cards-list/workshop-cards-list.component.ts
* Added initialization of the currentView from the url parameter
* Moved the update of the MapView in the FilterState from the child components to the parent component
> Fixed result map refresh

- src/app/shell/details/details-tabs/reviews/reviews.component.html
- src/app/shell/details/details-tabs/reviews/reviews.component.ts
> Fixed wrong display data about count reviews

- src/app/shell/personal-cabinet/shared-cabinet/messages/chat/chat.component.ts
#1942 
* Deleted the request to the server to receive the sent message
> Updated logic for receiving a message after sending

- src/app/shared/components/entity-checkbox-dropdown/entity-checkbox-dropdown.component.scss
- src/app/shared/models/application.model.ts
- src/app/shared/services/applications/application.service.ts
- src/app/shared/store/shared-user.actions.ts
- src/app/shared/store/shared-user.state.ts
- src/app/shared/styles/application-list.scss
- src/app/shared/styles/search.scss
- src/app/shell/admin-tools/admin-tools.component.html
- src/app/shell/admin-tools/data/admin-applications/admin-applications.component.html
- src/app/shell/admin-tools/data/admin-applications/admin-applications.component.spec.ts
- src/app/shell/admin-tools/data/admin-applications/admin-applications.component.ts
- src/app/shell/admin-tools/data/data-routing.module.ts
- src/app/shell/admin-tools/data/data.module.ts
- src/app/shell/personal-cabinet/shared-cabinet/applications/application-card/application-card.component.html
- src/app/shell/personal-cabinet/shared-cabinet/applications/application-card/application-card.component.ts
- src/app/shell/personal-cabinet/shared-cabinet/applications/applications.component.html
- src/app/shell/personal-cabinet/shared-cabinet/applications/applications.component.scss
- src/app/shell/personal-cabinet/shared-cabinet/applications/applications.component.ts
#1945 
* Added adminApplications component
* Added a search bar for applications
* Implemented search string filtering
* Added missing fields in the application card
> Issue#1945 admin applications

- src/app/shell/personal-cabinet/shared-cabinet/messages/chat/chat.component.ts
#1948 
Added listener for read messages
> Added listener for read messages

- src/app/shared/components/validation-hint/validation-hint.component.html
- src/app/shared/components/validation-hint/validation-hint.component.ts
#1952 
* Added a new condition that takes into account the case where the validation text is not shown after clicking on the input without changes
* Added a method that will trigger status updates once after changing the touched property
> Issue#1952-No-Validation-Messages

- src/app/shared/services/chat/chat.service.ts
- src/app/shared/store/chat.actions.ts
- src/app/shared/store/chat.state.ts
- src/app/shell/personal-cabinet/shared-cabinet/messages/chat/chat.component.ts
#1941
* Added loading of message history in a chat created by workshop ID
* Updated store for receiving messages by workshop ID
> Added loading messages history

- src/app/header/header.component.scss
- src/app/shared/components/category-card/category-card.component.scss
- src/app/shared/components/notifications/notifications.component.scss
* Updated header navigation
Before: 
After:
* Updated header menu
Before: 
After:
* Updated search-bar margin
Before:
After:
* Updated category-item
Before:
After:
> Main page styles fixes

- src/app/shared/enum/navigation-bar.ts
- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.html
Follow the link: (https://github.com/ita-social-projects/OoS-Frontend/issues/1837)
-fixed stepper on the form Update Provider Deputy
-fixed NavBarName on the form Update Provider Deputy
> [Provider Admins] -stepper should have completed state in the edit mode for valid form 

- src/app/shell/admin-tools/data/admins/create-admin/create-admin.component.html
removed star and added placeholder
> remove star

- src/app/shared/enum/enumUA/notifications.ts
- src/app/shell/admin-tools/data/history-log/history-log-table/history-log-table.component.html
- src/app/shell/admin-tools/data/history-log/history-log-table/history-log-table.component.ts
- src/app/shell/admin-tools/data/history-log/history-log.component.html
- src/app/shell/admin-tools/data/history-log/history-log.component.ts
- src/app/shell/admin-tools/platform/platform.component.ts
- src/app/shell/details/workshop-details/workshop-details.component.ts
- src/app/shell/personal-cabinet/provider/provider-admins/provider-admins.component.ts
- src/app/shell/personal-cabinet/shared-cabinet/applications/applications.component.ts
fixed pagination for the history of changes
fixed looping on quick tab changes
fixed notification missing for Not Provided License Status
https://user-images.githubusercontent.com/27493959/213750795-b7a7284c-835b-4b57-825d-ba796d47792c.mp4
> General bug fixes

- src/app/shared/components/filters-list/city-filter/city-filter.component.ts
* Fixed a bug with city switching when the filters did not put the coordinates of the new city
> Fixed bug with city switching

- src/app/shared/models/child.model.ts
- src/app/shared/services/achievements/achievements.service.ts
- src/app/shared/services/children/children.service.ts
* Updated child endpoints
* Updated the child model for the updated endpoints put ta post
> Child api refactor

- src/app/shell/admin-tools/data/history-log/history-log-filters/history-log-filters.component.html
- src/app/shell/admin-tools/data/history-log/history-log-filters/history-log-filters.component.scss
- src/app/shell/admin-tools/data/history-log/history-log-filters/history-log-filters.component.ts
- src/app/shell/admin-tools/data/history-log/history-log.component.html
- src/app/shell/admin-tools/data/history-log/history-log.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/uk.json
#2050 
* Deleted unnecessary data on the history-log page
* Replaced the two inputs for entering dates with one
* Added "All filters" option for select
* Added default value for the date control
* Added access modifiers
> Issue#2050 refactor history of changes page

- src/app/footer/footer.component.html
- src/app/footer/footer.component.scss
- src/app/footer/footer.component.spec.ts
- src/assets/i18n/en.json
- src/assets/i18n/uk.json
* Added trial message (screen 1)
* Added localization for trial message
* Updated mobile view of footer (screen 2)
> Added trial message to footer

- src/app/shared/components/workshop-card/workshop-card.component.html
#2073 
* Updated the condition for displaying the icons of the "favorites" workshops. Now the provider will not see the icons on the main page
> Removed the favorite icon for SP

- src/app/shared/components/filters-list/city-filter/city-filter.component.ts
#2092 
* Fixed a condition that caused searches to start with 4 letters
> Issue#2092 searching with 3 letters not working

- src/app/shared/components/provider-info/provider-info.component.html
#2102 
* Selected a property that has a designations of territorial units
> Changed property to display in the template

- src/app/shell/personal-cabinet/provider/create-provider-admin/create-provider-admin.component.ts
#2107 
* Added required validation for the necessary inputs
* Removed duplicate code
> Issue#2107-No-Validation-In-Inputs

- src/assets/i18n/uk.json
#2091 
* Fixed incorrect translation path
> Issue#2091-Incorrect-Translation

- src/app/shared/store/provider.state.ts
#2112 
* Changing the redirection path after registration new institution
> Changing the redirection path after registration

- src/app/shared/components/validation-hint/validation-hint.component.ts
- src/app/shell/personal-cabinet/provider/create-address-form/create-address-form.component.html
#2111
* Fixed incorrect display of maximum length 60 when set to 15
* Fixed the situation when the user is shown an hint about the incorrect pattern of the entered data after it has been corrected. This situation occurred only with two+ hints
> Fixed incorrect parameters in the validation hint

- src/app/shell/personal-cabinet/shared-cabinet/applications/application-card/application-card.component.scss
#2114 
* Corrected the alignment of the description of the workshop and the status of the request
> Updated application card view
