src/app/header/header.component.ts
src/app/shared/error-interceptors/http-error.interceptor.ts
src/app/shared/modals/registration/registration.module.ts
src/app/shared/store/user-registration.actions.ts
src/app/shared/store/user-registration.state.ts
src/environments/environment.prod.ts

1) CallAPi action was deleted
2) AuthFail action was created
3) Header contains the "handler" of AuthFail.
4)When there is no connection, the header displays snackbar with an error.

header contains action AuthFail handler+snackbar+callApi is deleted

---

src/app/app.module.ts
src/app/shared/registration/registration.module.ts
src/app/shared/store/app.actions.ts
src/app/shared/store/app.state.ts
src/app/shared/store/user.state.ts
src/app/shell/personal-cabinet/create.guard.spec.ts
src/app/shell/personal-cabinet/create.guard.ts
src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
src/app/shell/personal-cabinet/provider/create-workshop/create-workshop.component.ts
src/app/shell/shell-routing.module.ts

Create guard is modified so it tracks is the create-child forms dirty. 
If so, it opens a modal window, otherwise, you can just leave the page. If you click "submit" the modal window does not appear. 
Also, I took off the setTimeout because the time of response is enough before the redirection.

Create guard triggers only if the create-form is dirty

---

src/app/header/header.component.html
src/app/header/header.component.scss
src/app/header/header.component.spec.ts
src/app/shared/components/city-autocomplete/city-autocomplete.component.html
src/app/shared/components/city-autocomplete/city-autocomplete.component.scss
src/app/shared/components/filters-list/category-check-box/category-check-box.component.ts
src/app/shared/components/filters-list/searchbar/searchbar.component.html
src/app/shared/components/filters-list/searchbar/searchbar.component.scss
src/app/shared/components/full-search-bar/full-search-bar.component.html
src/app/shared/components/full-search-bar/full-search-bar.component.scss
src/app/shared/components/full-search-bar/full-search-bar.component.spec.ts
src/app/shared/components/full-search-bar/full-search-bar.component.ts
src/app/shared/components/navigation-bar/navigation-bar.component.ts
src/app/shared/shared.module.ts
src/app/shell/all-categories/all-categories.component.html
src/app/shell/all-categories/all-categories.component.scss
src/app/shell/all-categories/all-categories.component.spec.ts
src/app/shell/all-categories/all-categories.component.ts
src/app/shell/main/main.component.html
src/app/shell/result/result.component.html
src/app/shell/result/result.component.scss
src/app/shell/result/result.component.spec.ts
src/app/shell/shell-routing.module.ts
src/app/shell/shell.module.ts

If you click on "Переглянути всі" next to category card on the main page, you will be redirected to all-categories page, where categories card displayed. If you click on some specific category, you will be redirected to the result page.
The full search bar component combines city filter and search bar and applies styles for them. This component was reused in all the others+ checked the mobile view.

Create all categories page + search bar refactoring

---

src/app/shared/components/workshop-card/workshop-card.component.html
src/app/shared/components/workshop-card/workshop-card.component.spec.ts
src/app/shared/components/workshop-card/workshop-card.component.ts
src/app/shared/store/user.actions.ts
src/app/shared/store/user.state.ts
src/app/shared/styles/cards.scss
src/app/shared/styles/list-wrappers.scss
src/app/shell/personal-cabinet/applications/applications.component.html
src/app/shell/personal-cabinet/applications/applications.component.scss
src/app/shell/personal-cabinet/applications/applications.component.ts
src/app/shell/personal-cabinet/parent/create-application/create-application.component.ts
src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts
src/app/shell/personal-cabinet/parent/favorite-workshops/favorite-workshops.component.ts
src/app/shell/personal-cabinet/parent/parent-info/parent-info.component.html
src/app/shell/personal-cabinet/parent/parent-info/parent-info.component.scss
src/app/shell/personal-cabinet/parent/parent-info/parent-info.component.ts
src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.ts
src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.ts
src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.ts
src/app/shell/personal-cabinet/provider/create-workshop/create-teacher/create-teacher.component.ts
src/app/shell/personal-cabinet/provider/create-workshop/create-workshop.component.ts
src/app/shell/personal-cabinet/workshops/workshops.component.html
src/app/shell/personal-cabinet/workshops/workshops.component.scss
src/app/shell/personal-cabinet/workshops/workshops.component.spec.ts
src/app/shell/personal-cabinet/workshops/workshops.component.ts

1. Provider gets its workshops.
2. Parent gets applications that are filtered according to their status and displayed in an appropriate tab "Active/Non active". Also the applications are filtered according to the parent-children and for each child, its workshops are displayed as a card-list. 
3. Also action to leave the workshops was added to parent-workshops if the application status is approved.
4. Added wrappers if there are no workshops (TODO: ask the designer about the wrapper-design)
TODO: 
1. add appropriate chips to the application status of the workshops for both user roles.
2. Fix the workshop-action layout. For now, the action layout is moved down by bottom styles and it creates the fake space over the card and brokes the card's positioning.
3. Edit modal window if parent wants …

Display parent workshop

---

src/app/shared/components/child-card/child-card.component.html
src/app/shared/components/workshop-card/workshop-card.component.html
src/app/shared/components/workshop-card/workshop-card.component.scss
src/app/shared/styles/cards.scss
src/app/shell/workshop-details/workshop-page/workshop-page.component.html
src/app/shell/workshop-details/workshop-page/workshop-page.component.scss

Among all the icons, I found only the "approved" status, but not the others. Should we ask to replace these icons with those that we can have from mat-icons, or should we use images for displaying these statuses? 
https://www.angularjswiki.com/angular/angular-material-icons-list-mat-icon-list/

images are replaced with mat-icons

---

src/app/shared/enum/modal-confirmation.ts
src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts

the task: https://github.com/ita-social-projects/OoS-Backend/issues/191
Is implemented from scenario#2: "AND approval pop-up appears".

191 scenario#2

---

src/app/shell/personal-cabinet/applications/application-card/application-card.component.html
src/app/shell/personal-cabinet/applications/application-card/application-card.component.scss
src/app/shell/personal-cabinet/applications/application-card/application-card.component.ts

the issue 772: https://github.com/ita-social-projects/OoS-Frontend/issues/772
I tried many approaches to fix this bug, however only padding css property help to avoid this effect. It divides areas for "mouseenter" and "mouseleave" events.

[Personal cabinet] Broken pop-up on status hover

---

src/app/shared/components/workshop-card/workshop-card.component.html
src/app/shared/components/workshop-card/workshop-card.component.ts
src/app/shared/models/workshop.model.ts

the task https://github.com/ita-social-projects/OoS-Frontend/issues/813
display field "Форма власності" in the workshop card.

feat: add providerOwnership field to the card

---

src/app/shared/components/validation-hint-for-input/validation-hint-for-input.component.html
src/app/shared/components/validation-hint-for-input/validation-hint-for-input.component.ts
src/app/shell/personal-cabinet/parent/create-child/child-form/child-form.component.html
src/app/shell/personal-cabinet/parent/create-child/child-form/child-form.component.spec.ts
src/app/shell/personal-cabinet/parent/create-child/create-child.component.ts

Issue: https://github.com/ita-social-projects/OoS-Frontend/issues/850

Add input validation for add child form

---

src/app/shared/store/user.state.ts

Task https://github.com/ita-social-projects/OoS-Frontend/issues/995
Add redirection to '/personal-cabinet/administration' after successful creating provider admin

[Service provider] 'Адміністрування' tab - redirect to the personal cabinet after successfully provider Admin creating

---

src/app/shared/components/child-card/child-card.component.html
src/app/shared/components/child-card/child-card.component.scss
src/app/shared/components/child-card/child-card.component.ts
src/app/shared/components/image-form-control/image-form-control.component.ts
src/app/shared/components/teacher-card/teacher-card.component.html
src/app/shared/components/teacher-card/teacher-card.component.ts
src/app/shared/components/workshop-card/workshop-card.component.html
src/app/shared/components/workshop-card/workshop-card.component.scss
src/app/shared/components/workshop-card/workshop-card.component.ts
src/app/shared/constants/constants.ts
src/app/shared/styles/cards.scss
src/app/shell/workshop-details/workshop-page/workshop-page.component.ts

1. fix cover image for application/ map/ desktop view
2. new constants creared
3. code refactoring
4. fix for cover image displaying for map view

Cover image

---

src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.html
src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.scss
src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.spec.ts
src/app/shell/personal-cabinet/provider/create-provider/create-contacts-form/create-contacts-form.component.ts
src/app/shell/personal-cabinet/user-config/user-config-edit/user-config-edit.component.scss
src/app/shell/personal-cabinet/user-config/user-config-edit/user-config-edit.component.ts

1. add subscribtion on dity form for user config https://github.com/ita-social-projects/OoS-Frontend/issues/1351
2. disable city control when is the same address  https://github.com/ita-social-projects/OoS-Frontend/issues/1325
3. validation message is required filed https://github.com/ita-social-projects/OoS-Frontend/issues/1337

[High priority bug fix] - fix of dirty user config form, disable actual address, fix validations hints for address

---

src/app/shared/components/workshop-card/workshop-card.component.scss

#1713 
* Removed icon hiding
Before:
After:

 Fixed the view for details icon link

---

src/app/shared/components/confirmation-modal-window/reason-modal-window/reason-modal-window.component.html
src/app/shared/components/confirmation-modal-window/reason-modal-window/reason-modal-window.component.ts

#1763 
* Fixed validation check for modal
* Replaced the button disable control binding from the value of the control to its validation

Issue#1763 - Fixed validation check for modal

---

src/app/shell/personal-cabinet/shared-cabinet/applications/application-card/info-status/info-status.component.html
src/app/shell/personal-cabinet/shared-cabinet/applications/application-card/info-status/info-status.component.scss
src/app/shell/personal-cabinet/shared-cabinet/applications/applications.component.html
src/styles.scss

#1919 
* Fixed incorrect position of the pop-up menu
* Renamed style class to be more unique
* Removed the use of ::ng-deep for this pop-up menu, moving its styles into one common file

Issue#1919 worng pop-up position

---

src/app/shared/styles/search.scss
src/app/shell/personal-cabinet/shared-cabinet/applications/applications.component.scss

Fixed incorrect search bar styles
Before:
After:

Fixed incorrect positioning of the search bar

---

src/app/shell/admin-tools/data/provider-list/provider-list.component.html

* Fixed the wrong path when in the menu of a blocked provider, the button was labeled "block" and the unblocked one was "unblock"

Updated translated paths

---

.prettierrc.json
src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.ts

#2074 
* Disabled the ability to select the ownership in edit mode
* Removed unnecessary variable

Issue#2074 enabled ownership select in edit mode

---

src/app/header/header.component.html
src/app/shared/components/sidenav-menu/sidenav-menu.component.html
src/app/shared/services/provider/provider.service.ts
src/app/shared/services/workshops/user-workshop/user-workshop.service.ts
src/app/shared/store/provider.actions.ts
src/app/shared/store/provider.state.ts
src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.html
src/app/shell/personal-cabinet/provider/create-provider/create-info-form/create-info-form.component.ts
src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.html
src/app/shell/personal-cabinet/provider/create-provider/create-photo-form/create-photo-form.component.ts
src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.html
src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.spec.ts
src/app/shell/personal-cabinet/provider/create-provider/create-provider.component.ts
src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.html
src/app/shell/personal-cabinet/provider/create-workshop/create-about-form/create-about-form.component.ts
src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.html
src/app/shell/personal-cabinet/provider/create-workshop/create-description-form/create-description-form.component.ts
src/app/shell/personal-cabinet/provider/create-workshop/create-teacher/create-teacher.component.html
src/app/shell/personal-cabinet/provider/create-workshop/create-teacher/create-teacher.component.spec.ts
src/app/shell/personal-cabinet/provider/create-workshop/create-teacher/create-teacher.component.ts
src/app/shell/personal-cabinet/provider/create-workshop/create-teacher/teacher-form/teacher-form.component.html
src/app/shell/personal-cabinet/provider/create-workshop/create-teacher/teacher-form/teacher-form.component.ts
src/app/shell/personal-cabinet/provider/create-workshop/create-workshop.component.html
src/app/shell/personal-cabinet/provider/create-workshop/create-workshop.component.spec.ts
src/app/shell/personal-cabinet/shared-cabinet/create-form/create-form.component.ts

#2103 
* Fixed referencing a property by undefined
* The condition for connecting images feature has been changed: there is now a separate "images" flag for this instead of isRelease3
* Changed the order of private and public methods and properties: now they are not mixed up

Issue#2103 missing notifications

---

src/app/shared/components/institution-hierarchy/institution-hierarchy.component.html
src/app/shared/components/institution-hierarchy/institution-hierarchy.component.ts

#2126 
* Fixed bug with missing display of hierarchy fields
* Changed the names of some variables and methods to be more understandable
* Reduced the number of parameters in the onHierarchyLevelSelect method

Issue#2126 institution hierarchy fix
